customer-service:
  build: .
  ports:
    - "8080:8085"
  links:
    - redis:local-mongo
    - container-exporter:container-exporter
  environment:
    - MONGO_HOST=local-mongo
    - MONGO_PORT=27017
    - MONGO_DB=customer
cadvisor:
  image: google/cadvisor
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro
  ports:
     - "8099:8080"
mongo:
  image: mongo
prometheus:
  build: ./prometheus
  command: -config.file=/etc/prometheus/prometheus.yml -storage.local.memory-chunks=10000
  ports:
    - "9090:9090"
container-exporter:
  image: prom/container-exporter
  volumes:
    - /sys/fs/cgroup:/cgroup
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "9104:9104"