customer-service:
  build: .
  ports:
    - "8080:8085"
  links:
    - redis:local-redis
    - container-exporter:container-exporter
cadvisor:
  image: google/cadvisor
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro
  ports:
     - "8099:8080"
redis:
  image: redis
  ports:
    - "6379:6379"
prometheus:
  image: prom/prometheus
  volumes:
    - /prometheus.yml:/etc/prometheus/prometheus.yml
  command: -storage.local.memory-chunks=10000
  ports:
    - "9090:9090"
container-exporter:
  image: prom/container-exporter
  volumes:
    - /sys/fs/cgroup:/cgroup
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "9104:9104"